// <auto-generated />
using System;
using GiftLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiftLab.Migrations
{
    [DbContext(typeof(GiftLabDbContext))]
    partial class GiftLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GiftLab.Data.Entities.Account", b =>
            {
                b.Property<int>("AccountID")
                    .HasColumnType("int");

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<DateTime?>("CreateDate")
                    .HasColumnType("datetime");

                b.Property<string>("Email")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Fullname")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Password")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Phone")
                    .HasMaxLength(12)
                    .IsUnicode(false)
                    .HasColumnType("varchar(12)");

                b.Property<int?>("RoleID")
                    .HasColumnType("int");

                b.HasKey("AccountID");

                b.HasIndex("RoleID");

                b.ToTable("Accounts", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Attribute", b =>
            {
                b.Property<int>("AttributeID")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.HasKey("AttributeID");

                b.ToTable("Attributes", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.AttributesPrice", b =>
            {
                b.Property<int>("AttributesPriceID")
                    .HasColumnType("int");

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<int?>("AttributeID")
                    .HasColumnType("int");

                b.Property<int?>("Price")
                    .HasColumnType("int");

                b.Property<int?>("ProductID")
                    .HasColumnType("int");

                b.HasKey("AttributesPriceID");

                b.HasIndex("AttributeID");

                b.HasIndex("ProductID");

                b.ToTable("AttributesPrices", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Category", b =>
            {
                b.Property<int>("CatID")
                    .HasColumnType("int");

                b.Property<string>("Alias")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("Catname")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("Cover")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("Levels")
                    .HasColumnType("int");

                b.Property<string>("MetaDesc")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("MetaKey")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<int?>("Ordering")
                    .HasColumnType("int");

                b.Property<int?>("ParentID")
                    .HasColumnType("int");

                b.Property<bool>("Published")
                    .HasColumnType("bit");

                b.Property<string>("SchemaMarkup")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Thumb")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("Title")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.HasKey("CatID");

                b.ToTable("Categories", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Customer", b =>
            {
                b.Property<int>("CustomerID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                b.Property<bool?>("Active")
                    .HasColumnType("bit");

                b.Property<string>("Address")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Avatar")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<DateTime?>("Birthday")
                    .HasColumnType("datetime");

                b.Property<DateTime?>("CreateDate")
                    .HasColumnType("datetime");

                b.Property<string>("District")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Email")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("FullName")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("LocationID")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Password")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("Phone")
                    .HasMaxLength(12)
                    .IsUnicode(false)
                    .HasColumnType("varchar(12)");

                b.Property<string>("Ward")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("CustomerID");

                b.ToTable("Customers", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Order", b =>
            {
                b.Property<int>("OrderID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                b.Property<int?>("CustomerID")
                    .HasColumnType("int");

                b.Property<bool?>("Deleted")
                    .HasColumnType("bit");

                b.Property<string>("Note")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("OrderDate")
                    .HasColumnType("datetime");

                b.Property<bool?>("Paid")
                    .HasColumnType("bit");

                b.Property<DateTime?>("PaymentData")
                    .HasColumnType("datetime");

                b.Property<int?>("PaymentID")
                    .HasColumnType("int");

                b.Property<DateTime?>("ShipDate")
                    .HasColumnType("datetime");

                b.Property<int?>("TransactionStatusID")
                    .HasColumnType("int");

                b.Property<string>("ReceiverName")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("ReceiverEmail")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("ReceiverPhone")
                    .HasMaxLength(12)
                    .IsUnicode(false)
                    .HasColumnType("varchar(12)");

                b.Property<string>("ShipAddress")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("ShipDistrict")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ShipWard")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("ShippingFee")
                    .HasColumnType("int");

                b.HasKey("OrderID");

                b.HasIndex("CustomerID");

                b.HasIndex("TransactionStatusID");

                b.ToTable("Orders", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.OrderDetail", b =>
            {
                // ✅ FIX: Identity
                b.Property<int>("OrderDetailID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                b.Property<int?>("Discount")
                    .HasColumnType("int");

                b.Property<int?>("OrderID")
                    .HasColumnType("int");

                b.Property<int?>("OrderNumber")
                    .HasColumnType("int");

                b.Property<int?>("ProductID")
                    .HasColumnType("int");

                b.Property<int?>("Quantity")
                    .HasColumnType("int");

                b.Property<DateTime?>("ShipDate")
                    .HasColumnType("datetime");

                b.Property<int?>("Total")
                    .HasColumnType("int");

                b.Property<int?>("UnitPrice")
                    .HasColumnType("int");

                b.Property<string>("ProductName")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.HasKey("OrderDetailID");

                b.HasIndex("OrderID");

                b.ToTable("OrderDetails", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Product", b =>
            {
                b.Property<int>("ProductID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                b.Property<bool>("Active")
                    .HasColumnType("bit");

                b.Property<string>("Alias")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<bool>("BestSellers")
                    .HasColumnType("bit");

                b.Property<int?>("CatID")
                    .HasColumnType("int");

                b.Property<DateTime?>("DateCreated")
                    .HasColumnType("datetime");

                b.Property<DateTime?>("DateModified")
                    .HasColumnType("datetime");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("Discount")
                    .HasColumnType("int");

                b.Property<bool>("HomeFLag")
                    .HasColumnType("bit");

                b.Property<string>("MetaDesc")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("MetaKey")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<int?>("Price")
                    .HasColumnType("int");

                b.Property<string>("ProductName")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("ShortDesc")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Tags")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Thumb")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Title")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<int?>("UnitsInStock")
                    .HasColumnType("int");

                b.HasKey("ProductID");

                b.HasIndex("CatID");

                b.ToTable("Products", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Role", b =>
            {
                b.Property<int>("RoleID")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("RoleName")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("RoleID");

                b.ToTable("Roles", (string)null);
            });

            modelBuilder.Entity("GiftLab.Data.Entities.TransacStatus", b =>
            {
                b.Property<int>("TransactStatusID")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("TransactStatusID");

                b.ToTable("TransacStatus", (string)null);

                b.HasData(
                    new { TransactStatusID = 1, Status = "Pending", Description = "Đang chờ xử lý" },
                    new { TransactStatusID = 2, Status = "Processing", Description = "Đang xử lý" },
                    new { TransactStatusID = 3, Status = "Shipped", Description = "Đang giao hàng" },
                    new { TransactStatusID = 4, Status = "Completed", Description = "Hoàn thành" },
                    new { TransactStatusID = 5, Status = "Cancelled", Description = "Đã hủy" }
                );
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Account", b =>
            {
                b.HasOne("GiftLab.Data.Entities.Role", "Role")
                    .WithMany("Accounts")
                    .HasForeignKey("RoleID")
                    .HasConstraintName("FK_Accounts_Roles");

                b.Navigation("Role");
            });

            modelBuilder.Entity("GiftLab.Data.Entities.AttributesPrice", b =>
            {
                b.HasOne("GiftLab.Data.Entities.Attribute", "Attribute")
                    .WithMany("AttributesPrices")
                    .HasForeignKey("AttributeID")
                    .HasConstraintName("FK_AttributesPrices_Attributes");

                b.HasOne("GiftLab.Data.Entities.Product", "Product")
                    .WithMany("AttributesPrices")
                    .HasForeignKey("ProductID")
                    .HasConstraintName("FK_AttributesPrices_Products");

                b.Navigation("Attribute");
                b.Navigation("Product");
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Order", b =>
            {
                b.HasOne("GiftLab.Data.Entities.Customer", "Customer")
                    .WithMany("Orders")
                    .HasForeignKey("CustomerID")
                    .HasConstraintName("FK_Orders_Customers");

                b.HasOne("GiftLab.Data.Entities.TransacStatus", "TransactionStatus")
                    .WithMany("Orders")
                    .HasForeignKey("TransactionStatusID")
                    .HasConstraintName("FK_Orders_TransacStatus");

                b.Navigation("Customer");
                b.Navigation("TransactionStatus");
            });

            modelBuilder.Entity("GiftLab.Data.Entities.OrderDetail", b =>
            {
                b.HasOne("GiftLab.Data.Entities.Order", "Order")
                    .WithMany("OrderDetails")
                    .HasForeignKey("OrderID")
                    .HasConstraintName("FK_OrderDetails_Orders");

                b.Navigation("Order");
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Product", b =>
            {
                b.HasOne("GiftLab.Data.Entities.Category", "Cat")
                    .WithMany("Products")
                    .HasForeignKey("CatID")
                    .HasConstraintName("FK_Products_Categories");

                b.Navigation("Cat");
            });

            modelBuilder.Entity("GiftLab.Data.Entities.Attribute", b => { b.Navigation("AttributesPrices"); });
            modelBuilder.Entity("GiftLab.Data.Entities.Category", b => { b.Navigation("Products"); });
            modelBuilder.Entity("GiftLab.Data.Entities.Customer", b => { b.Navigation("Orders"); });
            modelBuilder.Entity("GiftLab.Data.Entities.Order", b => { b.Navigation("OrderDetails"); });
            modelBuilder.Entity("GiftLab.Data.Entities.Product", b => { b.Navigation("AttributesPrices"); });
            modelBuilder.Entity("GiftLab.Data.Entities.Role", b => { b.Navigation("Accounts"); });
            modelBuilder.Entity("GiftLab.Data.Entities.TransacStatus", b => { b.Navigation("Orders"); });
#pragma warning restore 612, 618
        }
    }
}
